Implemented prime function with assertions
tejasprabhucc/cc5-tejas-assignments pull request #1
Opened 2024-03-27 10:34 UTC by tejasprabhucc

In this implementation prime function has 2 pre-conditions, 
1.  to check if the parameter is number and 
2. to check if the number is less than 2
Post-condition check it is not a prime number.

Output:
0 is not a prime number
1 is not a prime number
2 is a prime number
3 is a prime number
5 is a prime number
10 is not a prime number
11 is a prime number
99999 is not a prime number
Hello is not a number. Give a number as a parameter

2024-03-27 12:01 UTC, shripada requested changes
Can you check you PR, I am not seeing anyhting credible. May be you missed to push?

2024-03-27 12:15 UTC, tejasprabhucc commented
> Can you check you PR, I am not seeing anyhting credible. May be you missed to push?

Sir I thing the code has been collapsed, could you please expand it.

2024-03-28 12:00 UTC, shripada requested changes

2024-03-28 12:00 UTC, shripada commented on src/prime.js
> +
add assertions for isPrime too

2024-03-28 12:00 UTC, shripada commented on src/prime.js
> +assert.strictEqual(generatePrimeSeries(5), [2, 3, 5, 7, 11], "Couldn't generate prime series");
assert message is wrong

2024-03-28 12:00 UTC, shripada commented on src/prime.js
> +assert.strictEqual(generatePrimeSeries(5), [2, 3, 5, 7, 11], "Couldn't generate prime series");
Also add asserts, for cases where expect generatePrimes to throw. See `assert.throws`

2024-04-01 09:16 UTC, merged